name: SA DockerBuild

on:
  # Allows manual run of this workflow from the Actions tab (on any branch)
  workflow_dispatch:

# For debugging
# on:
#   push:
#     branches: ''

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Diagnostics
      run: |
        docker system df
    - name: Host System Diagnostics
      run: |
        df -h
        du -sh *
    - name: Docker Cleanup
      run: |
        docker system prune -af
        docker volume prune -f
        docker builder prune -f
    - name: Builder Bootstrap
      run: docker buildx create --name devBuilder --use --bootstrap
    - name: Build the Docker Image
      run: docker buildx build -f DevUtils/docker/Dockerfile.sa --platform linux/amd64,linux/arm64 --tag swirlai/swirl-search:develop-sa --push .

    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: log-files
        path: |
          logs/
          /var/log/syslog*
