name: EXPERIMENTAL Latest Spyglass Docker Build

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# For debugging
# on:
#   push:
#     branches: ''

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --no-cache -t swirlai/spyglass:fork-x  -f Dockerfile.fork.spg .
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Push the Docker image
      run: docker push swirlai/spyglass:fork-x
    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: log-files
        path: |
          logs/
          /var/log/syslog*
